name: generate-registry

on:
  push:
    branches:
      - master
    paths:
      - 'plugins/**'
      - 'tools/generate_registry.js'
      - '.gitverse/workflows/generate-registry.yml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate registry
        run: node tools/generate_registry.js --sync-checksums

      - name: Commit registry changes
        run: |
          if git diff --quiet; then
            echo "No changes"
            exit 0
          fi
          git config user.name "gitverse-bot"
          git config user.email "bot@gitverse.local"
          git add plugins/**/plugin-manifest.json registry/plugins-index.json
          git commit -m "chore: regenerate plugins index"
          git push origin HEAD:master
